language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- coverage run --source=pygrocy setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: SebRut
  password:
    secure: NirAdoq7axmkLmHaT4cQVD+v3IP6azASfUQd5wnHVgFbOh+lJzNuGKekrkUeeKVCcq2afQ9wOFGPhPTSjJffE6i6C6yU+OPcXcRthFpXKG3zRGhZDDKlEtHs11JZoJjCPc223YdEI7uS442rH3OlZlBUA1KIQG61qzsg1r9cCUx0A7Fz9Mt7hXChmAzUO3UKnm+2PAHe0nkBivYdszvxO4jvIIWDy2fWuVYTbUgg+q+cxc7APVA1SFJoSrDOGaYS5MTNjqhUS8CGIkrogeQ76SAV09kHqH92QG/FeXNz6e2g06Td7sBCpmF0ypD9MalzhSLJb6B6/7ETojcKPgPXvlodv67EpqNI2nN1UAlAf7T9I13dd5RXFnU350NkcPPJuBIIX+kXTbUisENuFnXWy3d3QVqi0IVgKaX/e8yi0PQZcN0/MM5ine96Jb+ocgePBKgJ7Dj4cvUWGjMgpeJ4lWB0G971KKz5xxBY52c5NOqZ11Idtqqhx/JxW12cIkqyaM5h+pBqCBhFI8nSyGp2Gnir/I7bk/0Uim+HYLqFGwa7fNMC7Lrl4Y9gOC7JiUIAtlIUjGVoKsY+Tt4g17STGbhztNid/ExJnnSMsS/gdR6cn+C3V69nsGu9gXG7fdo+WXiQRPyw3NL9KRQOk2Zlfr8aPqW45sMS04M+oTuYoXI=
  on:
    tags: true
  skip_existing: true
  skip_cleanup: true
