language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- coverage run --source=pygrocy setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: SebRut
  password:
    secure: M8CyNVDgnwC6x3gX1JfSGSb/VGiPGyJLLWlWg/EEl2Ae00hXNyU4jLnc+Iv8WdyFBoQj7RZ4tTEppKzFLU8OLwq457cSZx3MqKOqhW+qOa1eQ/CHf/AjmlFnt6nneo6VYLXLCBJZ/WFm26PpbwPd3z4DWy+wS3s0gtomVbKxZkJmer/SkcfzAXkKgQdzYybetcaoX0mNUCNtp78iEihyVVhA3tECrZW2wg+wEj3GOj7I/NEvQOy00OxMHRdbp059A/173wrqXlw8iWHqACE0YLpqSTQxL7yvkjSKeZrK3psmCZdMby2BHryXYd/3l7diOad3oRzbQceZCQwcfZ7Q48dvS5HtfBIpCnahRO5QSORVn3Y2Qq+IFym536bBwMjRKglDqcx/v2uaA1AYDsL5wsEev3wnm6YvLTT1OTAa3Z0ZG2ggA7IKl5gDEbmTELE5GXzHVhZX0Yl/vGJIDPLRECIZv7I/SQ9Tr9238+zOp4DMHGGXrRe3jwLe8ZFu++0rveD4r/G8swtCgn3mypnILOgE1z9CIbBm5238jBqBeKs1BMjzXXOeZuVOxh+lg0FtNgeJrIF9O4cnY5mpDd4tgrtONVW67jipONEiTN9WCOnZoq1o3MHQrt+LRz4B9FTmoz/Sx9SUXqkMF8PjsmLYtQ4HcbWVnV3omuq3XJpbC6Y=
  on:
    tags: true
  skip_existing: true
  skip_cleanup: true
